### ISSUE TITLE
Implement the initial kafka producer

### ISSUE THREAD

**Issue by zsofiak96** [zsofiak96/kafka-streaming-demo#3]
# Description
The initial kafka producer fetches the [OpenWeather API](https://openweathermap.org/) every 15 minutes.
The raw data is written to a timeseries database. So we store raw data for historical purposes. And it is also immediately written into a kafka stream with topic `weather`.

# Tasks
- [x] set up fetching OpenWeather with `requests`
- [x] parse the data into a model
- [x] deserialize it for ingestion into kafka
- [ ] #5
- [x] set up the kafka admin that creates a topic if it doesn't exist
- [ ] #6
- [ ] #7
- [ ] #8
- [x] extend the documentation
